<?php

/**
 * @var array $properties
 * @var int $selectedPropertyId
 * @var int $zoom
 * @var float $selectedLatitude
 * @var float $selectedLongitude
 */ ?>

<html>
<head>
    <title>Mallorcasa</title>
    <style>

        body{
            background: gray;
        }
        table, th, td {
            border: 2px solid black;
            padding-left: 12px;
            padding-right: 12px;
            color: black;
            margin: auto;
        }

        th{
            color: yellow !important;
        }

        h1{
            text-align: center;
            font-family: "Droid Sans Mono";
            color: yellow;
            font-weight: bold;
        }

        form{
            border 1px solid;
        }

        a{
            text-align: right;
        }

    </style>
</head>
<body>
<section class="head">
    <div class="container">
        <?php if (isset($_SESSION["userMail"])) { ?>
            <h2>Loged in as : <?php echo $_SESSION["userMail"]?></h2>
            <!-- AQUI FALTA METER MIS PROPIEDADES, CON EL CONTROLADOR DE USUARIO -->
            <a href="../Controllers/list.php">Todas las propiedades</a>
            <a href="../Controllers/logoutController.php">Logout</a>
        <?php } else { ?>
            <a href="../Controllers/loginController.php">Login</a>
            <a href="../Controllers/signupController.php">Signup</a>

        <?php } ?>
    </div>
</section>
<table>
    <h1>Listado de mis propiedades</h1>
    <tr>
        <th>ID</th>
        <th>Imagen</th>
        <th>Ciudad</th>
        <th>Surface</th>
        <th>Rooms</th>
        <th>Bathrooms</th>
        <th>Zipcode</th>
        <th>Price</th>
    </tr>

    <?php
    foreach ($properties as $property){
        echo "<tr>";
        echo "<td>" ,$property->getId() ,"</td>";
        echo "<td>", $property->getImages()[0]->getUrl() ,"</td>";
        echo "<td>", $property->getCity()->getName() ,"</td>";
        echo "<td>", $property->getSurface() ,"</td>";
        echo "<td>", $property->getRooms() ,"</td>";
        echo "<td>", $property->getBathrooms() ,"</td>";
        echo "<td>", $property->getZipcode() ,"</td>";
        echo "<td><a href='singleProperty.php?id=" . $property->getId() . "' target='_blank'>", $property->getPrice(), "</a></td>";
        echo "<tr>";
    }
    ?>
</table>
</body>
</html>