<!DOCTYPE html>
<html>
<head>
    <title>Lista de los hoteles.</title>
    <style>
        body{
            background: lightblue;
        }
        table, th, td {
            border: 2px solid black;
            color: black;
            margin: auto;
        }


    </style>
</head>

<body>
    <h1>Lista de hoteles.</h1>
    <?php
    if (isset($_SESSION["user"])){ ?>
    <h2><span>Loged in as: <?php echo $_SESSION["user"] ?> </span></h2>
    <?php } ?>

    <table>
        <tr>
            <th>Hotel</th>
            <th>Estrellas</th>
            <th>Localidad</th>
            <th>Imagen</th>
        </tr>
        <?
        foreach($hoteles as $hotel){
            echo "<tr>";
            echo "<td>" , $hotel->getNombre() , "</td>";
            echo "<td>" , $hotel->getEstrellas() , "</td>";
            echo "<td>" , $hotel->getLocalidad() , "</td>";
            echo "<td><a href='listSingle.php?id=" . $hotel->getId() . "' target='_blank'><img src='../imagenes/", $hotel->getImagen(), "'></a></td>";
            echo "</tr>";
        }

        ?>
    </table>
</body>

</html>